package com.gsr.myschool.common.shared.type;

public enum EmailType {
    REGISTRATION,
    ACTIVATION,
    RELANCE,
    FORGOTTEN_PASSWORD,
    DOSSIER_RECEIVED,
    DOSSIER_INCOMPLETE,
    DOSSIER_COMPLETE,
    PIECES_RECEIVED,
    NOT_ACCEPTED_FOR_TEST,
    SESSION_CANCELED,
    CONVOCATED_FOR_TEST;
}
